
version: "3.5"

services:
    scrypted:
        image: koush/scrypted
        container_name: scrypted
        restart: unless-stopped
        network_mode: host
        volumes:
            - ~/.scrypted/volume:/server/volume
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
